# Part 1. Python Basics


## Task 1

In [1]:
list1 = ['apple','banana','cherry']
list2 = [1,5,7,9,3]
list3 = [True,False,False]

In [2]:
thislist = ['apple','banana','cherry']
print(thislist[0])
print(thislist[-1])
print(thislist[-2])


apple
cherry
banana


In [3]:
thislist = ['apple','banana','cherry','orange','kiwi','melon','mango']
print(thislist[2:5])
print(thislist[2:-2])

['cherry', 'orange', 'kiwi']
['cherry', 'orange', 'kiwi']


In [4]:
thislist = list1.copy()
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry', 'orange']


In [5]:
thislist = list1.copy()
thislist.insert(1,'orange')
print(thislist)

['apple', 'orange', 'banana', 'cherry']


In [6]:
thislist = list1.copy()
tropical = ['mango','pineapple','papaya']
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']


In [7]:
thislist = list1.copy()
thislist.remove("banana")
print(thislist)

['apple', 'cherry']


In [8]:
thislist = list1.copy()
for x in thislist:
    print(x)


apple
banana
cherry


In [9]:
for i in range(len(thislist)):
    print(thislist[i])

apple
banana
cherry


In [10]:
thistuple = ('apple','banana','cherry','apple')
print(thistuple)

('apple', 'banana', 'cherry', 'apple')


In [11]:
thistuple = thistuple + ('orange','kiwi','melon','mango')
print(thistuple[1])
print(thistuple[-1])
print(thistuple[2:5])

banana
mango
('cherry', 'apple', 'orange')


In [12]:
fruits = ('apple','banana','cherry')
green,yellow,red = fruits
print(green,yellow,red)

apple banana cherry


In [13]:
for x in fruits:
    print(x)

apple
banana
cherry


In [14]:
for x in range(len(fruits)):
    print(thistuple[x])

apple
banana
cherry


In [15]:
thisdict = {
    'brand':'ford',
    'model':'Mustang',
    'year':1964
}
print(thisdict)
print(thisdict['brand'])

{'brand': 'ford', 'model': 'Mustang', 'year': 1964}
ford


In [16]:
print(thisdict.keys())
print(thisdict.values())
print(thisdict.items()
     )

dict_keys(['brand', 'model', 'year'])
dict_values(['ford', 'Mustang', 1964])
dict_items([('brand', 'ford'), ('model', 'Mustang'), ('year', 1964)])


In [17]:
thisdict['color'] = 'red'
print(thisdict)

{'brand': 'ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


In [18]:
thisdict.update({'year':2021})
thisdict.update({'color':'red'})
print(thisdict)

{'brand': 'ford', 'model': 'Mustang', 'year': 2021, 'color': 'red'}


In [19]:
test = thisdict.copy()
test.pop('model')
test

{'brand': 'ford', 'year': 2021, 'color': 'red'}

In [20]:
for x in thisdict.keys():
    print(x)

for x in thisdict.values():
    print(x)

for x,y in thisdict.items():
    print(x,y)

brand
model
year
color
ford
Mustang
2021
red
brand ford
model Mustang
year 2021
color red


# Part 2. Vector and Matrix

In [21]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/cis3715-cars-dataset/README.md
/kaggle/input/cis3715-cars-dataset/Lab01/Lab1_PythonBasics.ipynb
/kaggle/input/cis3715-cars-dataset/Lab01/cars.csv
/kaggle/input/cis3715-cars-dataset/Lab01/Lab1_vector_and_matrix.ipynb
/kaggle/input/cis3715-cars-dataset/Lab01/LabAssignment1.pdf
/kaggle/input/cis3715-cars-dataset/Dataset/housing_missing.csv
/kaggle/input/cis3715-cars-dataset/Dataset/cars.csv
/kaggle/input/cis3715-cars-dataset/Dataset/daily-min-temperatures.csv
/kaggle/input/cis3715-cars-dataset/Dataset/spam.csv


In [22]:
import numpy as np
import pandas as pd

cars = '/kaggle/input/cis3715-cars-dataset/Lab01/cars.csv'
df = pd.read_csv(cars)
X = df.values[:,1:-1]
print(X.shape)
print(X)

(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


In [23]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


In [24]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## Task 2

### 2.1 Get the first column and the second to last column from X

In [25]:
df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0         130   
1          Buick Skylark 320  15.0          8         350.0         165   
2         Plymouth Satellite  18.0          8         318.0         150   
3              AMC Rebel SST  16.0          8         304.0         150   
4                Ford Torino  17.0          8         302.0         140   

   Weight  Acceleration  Model Origin  
0    3504          12.0     70     US  
1    3693          11.5     70     US  
2    3436          11.0     70     US  
3    3433          12.0     70     US  
4    3449          10.5     70     US

In [26]:
first = df.iloc[:,1]
second = df.iloc[:,-2]
print(first)
print(second)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
401    27.0
402    44.0
403    32.0
404    28.0
405    31.0
Name: MPG, Length: 406, dtype: float64
0      70
1      70
2      70
3      70
4      70
       ..
401    82
402    82
403    82
404    82
405    82
Name: Model, Length: 406, dtype: int64


### Perform following operations on these two vectors and print the result

In [27]:
# 1. addition and subtraction
print(first + second)
print(first - second)

0       88.0
1       85.0
2       88.0
3       86.0
4       87.0
       ...  
401    109.0
402    126.0
403    114.0
404    110.0
405    113.0
Length: 406, dtype: float64
0     -52.0
1     -55.0
2     -52.0
3     -54.0
4     -53.0
       ... 
401   -55.0
402   -38.0
403   -50.0
404   -54.0
405   -51.0
Length: 406, dtype: float64


In [28]:
# 2. element-wise multiplication
print(first* second)

0      1260.0
1      1050.0
2      1260.0
3      1120.0
4      1190.0
        ...  
401    2214.0
402    3608.0
403    2624.0
404    2296.0
405    2542.0
Length: 406, dtype: float64


In [29]:
# 3. inner product
print(first.dot(second))

718009.0999999999


In [30]:
# 4. three norms
# https://iq.opengenus.org/norm-method-of-numpy-in-python/
print(np.linalg.norm(first,1))
print(np.linalg.norm(first,2))
print(np.linalg.norm(first,float("inf")))

9358.8
494.28813459357895
46.6


In [31]:
# compute the distance between these two vectors
print(np.linalg.norm(first-second))

1074.3316806275425


### 2.3 Get the first three columns and the last three columns from X

In [32]:
A,B = df.iloc[:,1:4],df.iloc[:,-4:-1]
A.head()

MPG  Cylinders  Displacement
0  18.0          8         307.0
1  15.0          8         350.0
2  18.0          8         318.0
3  16.0          8         304.0
4  17.0          8         302.0

In [33]:
B.head()

Weight  Acceleration  Model
0    3504          12.0     70
1    3693          11.5     70
2    3436          11.0     70
3    3433          12.0     70
4    3449          10.5     70

### Perform following operations on these two matrices and print the result

In [34]:
# addition and subtraction
print(A.to_numpy()+B.to_numpy())
print(A.to_numpy()-B.to_numpy())

[[3522.    20.   377. ]
 [3708.    19.5  420. ]
 [3454.    19.   388. ]
 ...
 [2327.    15.6  217. ]
 [2653.    22.6  202. ]
 [2751.    23.4  201. ]]
[[-3.486e+03 -4.000e+00  2.370e+02]
 [-3.678e+03 -3.500e+00  2.800e+02]
 [-3.418e+03 -3.000e+00  2.480e+02]
 ...
 [-2.263e+03 -7.600e+00  5.300e+01]
 [-2.597e+03 -1.460e+01  3.800e+01]
 [-2.689e+03 -1.540e+01  3.700e+01]]


In [35]:
# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = B.T
C.shape

(3, 406)

In [36]:
# 3. compute the product between A and C, and print the result and its shape
dot = C.dot(A)
print(dot)
print(dot.shape)

                      MPG  Cylinders  Displacement
Weight        25614040.90  7149030.0   269175402.0
Acceleration    149295.04    33484.7     1160836.3
Model           718009.10   167835.0     5943079.0
(3, 3)


In [37]:
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = A.T
D.shape

(3, 406)

In [38]:
# 5. compute the product between D and B, and print the result and its shape
dot = D.dot(B)
print(dot)
print(dot.shape)

                   Weight  Acceleration      Model
MPG            25614040.9     149295.04   718009.1
Cylinders       7149030.0      33484.70   167835.0
Displacement  269175402.0    1160836.30  5943079.0
(3, 3)
